### ISSUE TITLE
System.NullReferenceException Crash

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [terrybrashaw/HLDJConverter#4]
[HLDJConverterCrashLog.txt](https://github.com/inlinevoid/HLDJConverter/files/46441/HLDJConverterCrashLog.txt)

**Comment by inlinevoid** [comment]
Can you link me the video that caused the crash?

**Comment by MegaApuTurkUltra** [comment]
https://www.youtube.com/watch?v=UgN4vzJredM was the one it crashed on
https://www.youtube.com/watch?v=5IW9B82ZZ8k and https://www.youtube.com/watch?v=pQjAhTzsaIU were completed in the queue at the time.
<sub><sup>(don't judge please)</sup></sub>

When I opened HLDJConverter and dragged it in again then it worked.

**Comment by inlinevoid** [comment]
Can't seem to reproduce the issue, is it happening often? I'll try putting in some extra null checks in the next version.

**Comment by MegaApuTurkUltra** [comment]
It's only happened once. If it happens again, I'll post the log.
