### ISSUE TITLE
Can't open version 1.5

### ISSUE THREAD

**Issue by TheRangor** [terrybrashaw/HLDJConverter#5]
was going to upgrade from v1.2 to 1.5 to see if the youtube link errors would go away and I can't open version 1.5. Running windows 10 pro.

It just forever shows the loading cursor and nothing happens.

**Comment by inlinevoid** [comment]
Are you on a 32-bit or 64-bit machine?  And try installing .NET 4.6 https://www.microsoft.com/en-us/download/details.aspx?id=48130

**Comment by TheRangor** [comment]
I'm on a 64-bit machine. 

.NET 4.6 is already installed on my machine.

**Comment by inlinevoid** [comment]
Is a file called `HLDJConverterCrashLog.txt` being created in the same directory as HLDJConverter?  If so, send me the link inside it at the top.

**Comment by inlinevoid** [comment]
Also, what's the primary language you have installed? (language as in English, German, etc.)

**Comment by TheRangor** [comment]
Only files in folder are ffmpeg and hldjconverter, no crash log.

Also primary language is English.

Another thing to note is that after trying to open the program I can't delete the HLDJconverter.exe. It says its in use and this persists till I restart my machine.

**Comment by inlinevoid** [comment]
If HLDJConverter is stuck running, you should be able to easily terminate it through Task Manager.  I'll make some changes and release a (hopefully) fixed version tomorrow.  Too tired atm.

**Comment by TheRangor** [comment]
I tried closing the program via Task Manager, however I couldn't see any task labeled HLDJconverter which is why I had to restart my pc.

**Comment by TheRangor** [comment]
Just an update, I think the problem might be ffmpeg.exe. If double click on the ffmpeg.exe alone, it causes the process hanging. I can't see the ffmpeg.exe in the task manager, but if it do Tasklist in command line, I can see 3 instances of ffmpeg. All 3 instances of ffmpeg have 80k mem usage.

I don't know if this is an issues on my end or with the ffmpeg.exe

**Comment by inlinevoid** [comment]
Hey, sorry I've been sick the past few days.

It's strange that FFmpeg would hang when trying to run it.  If no commands are passed to it, it should just close instantly after running...And FFmpeg is a very reliable piece of software, no idea why it would hang!

That wouldn't be the cause of HLDJConverter hanging, though.  FFmpeg isn't run at all until a song is converted.

[Try this build (overwrite the current HLDJConverter.exe you have)](https://github.com/inlinevoid/HLDJConverter/releases/download/1.5.1/HLDJConverter.exe)

I reverted the .NET version back to 4.5 and removed some 4.6-specific code.  If that doesn't work, then it might be something on your side.  Antivirus maybe?

**Comment by inlinevoid** [comment]
Actually I just noticed you said you changed from 1.2, a lot more has changed since then so it could be a large number of things I guess.

Try deleting your config file as well (`HLDJConverterConfig.cfg`)
